### ISSUE TITLE
Empty title!

### ISSUE THREAD

**Issue by Rexcantor** [Cybermaxke/MerchantsAPI#2]
I recently used this resource on my plugin and I don't know why, but the title doesn't show up:
https://gyazo.com/d3b04d0863995167ef9b83506f775ba3

My code:

http://pastebin.com/B893NUYM

**Comment by Rexcantor** [comment]
I also can't execute trades, when I close the inventory, the items come back.

Error log (inverted): http://pastebin.com/u4u5AYtd

**Comment by Cybermaxke** [comment]
@Rexcantor 
Can you provide the complete server log?

**Comment by Rexcantor** [comment]
Hum... ignore the second one. It's a event that is blocking it, because I tested it out game and it's working fine. About the first one, the only error that appears on console it's the one I gave you.

Complete log: http://pastebin.com/947TW8f4

**Comment by Cybermaxke** [comment]
@Rexcantor I fixed the error you had, the title will probably still be empty because I haven't looked into that. Could you test if the latest version works?

**Comment by Rexcantor** [comment]
What error? The only error I have is the title... But I will test it.

**Comment by Cybermaxke** [comment]
@Rexcantor The errors that are in the log aren't related to the title.

**Comment by Rexcantor** [comment]
Oh, ok

**Comment by Rexcantor** [comment]
Ok, it worked. I haven't seen any errors on console about InventoryOpenEvent.
But now I have another problem. The carrot doesn't work. The result slot is empty and when I try to buy, my minecraft crashes. Thanks for the fix, I don't like my console spammed my errors.

**Comment by Cybermaxke** [comment]
@Rexcantor Can you send me the client crash log?

**Comment by Cybermaxke** [comment]
Please reopen this issue if the problem still occurs.
