### ISSUE TITLE
Cannot change the color of the title

### ISSUE THREAD

**Issue by kh498** [Cybermaxke/MerchantsAPI#4]
I've tried
`merchant = api.newMerchant(ChatColor.YELLOW + "Test");`
and
`merchant.setTitle(ChatColor.YELLOW + "Test");`

**Comment by Z3tr0nix** [comment]
merchant.setTitle(ChatColor.YELLOW + "Test");

**Comment by kh498** [comment]
Yeah, as you can see I've done that (just forgot the last quotation mark)

**Comment by Z3tr0nix** [comment]
try using it without color codes :/

**Comment by Cybermaxke** [comment]
Can you try to use `setTitle("{\"text\":\"Test\",\"color\":\"red\"}", true)`

**Comment by kh498** [comment]
That worked @Cybermaxke
