### ISSUE TITLE
New merchant error :/

### ISSUE THREAD

**Issue by Z3tr0nix** [Cybermaxke/MerchantsAPI#7]
`24.12 16:20:31 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]
24.12 16:20:31 [Server] INFO Caused by: java.lang.NullPointerException
24.12 16:20:31 [Server] INFO at fc.regionwars.main.RegionWars.SpawnArmorGearTrader(RegionWars.java:434) ~[?:?]
24.12 16:20:31 [Server] INFO at fc.regionwars.main.RegionWars.StartEvent(RegionWars.java:394) ~[?:?]
24.12 16:20:31 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_112]
24.12 16:20:31 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_112]
24.12 16:20:31 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_112]
24.12 16:20:31 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_112]
24.12 16:20:31 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.9.2.jar:git-Spigot-e000104-4cb3258]
24.12 16:20:31 [Server] INFO ... 20 more`
that is all the stacktrace
Line 394 of method SpawnArmorGearTrader:
`		Merchant Trader = api.newMerchant("§bArmorer");`
Is this a prob with ur plugin or I am using it wrong?

**Comment by Cybermaxke** [comment]
Make sure that the `api` instance isn't null.

**Comment by Z3tr0nix** [comment]
MerchantAPI api = Merchants.get();

**Comment by Cybermaxke** [comment]
Can you provide me your code?

**Comment by Z3tr0nix** [comment]
Yes, my class:
IGNORE THE MESSYNESS
http://pastebin.com/fBELrTFh

**Comment by Z3tr0nix** [comment]
So?

**Comment by megamichiel** [comment]
In your stacktrace: "spigot-1.9.2.jar" 
That's not the latest build of 1.9 (1.9.4 is). I saw that MerchantAPI only makes it for the latest build.

**Comment by Cybermaxke** [comment]
Yes, only 1.9.4 is supported, please update to the latest version and retest. I will reopen this issue if the problem still occurs.
