### ISSUE TITLE
Dropbox 429 Error

### ISSUE THREAD

**Issue by stuntguy3000** [Cybermaxke/MerchantsAPI#9]
![image](https://cloud.githubusercontent.com/assets/1522389/24836372/7106fed4-1d59-11e7-82d5-a9a97c826b29.png)

**Comment by Cybermaxke** [comment]
Oh Dropbox :(
I moved the downloads to a different location: https://cybermaxke.stackstorage.com/s/XtfYWE3GiQhCxj5
Thanks for letting me know!
